# Auto Gitmsg 配置文件示例
# 将此文件复制为 .gitmsg.yaml 并根据需要修改

# OpenAI API 兼容的 API 基础 URL
# 默认: https://api.openai.com/v1
# 示例（使用代理或第三方服务）:
# api_base: https://api.example.com/v1
api_base: https://api.openai.com/v1

# API Key（建议使用环境变量 OPENAI_API_KEY）
# api_key: sk-xxx

# 使用的模型
model: gpt-4o-mini

# 生成温度 (0.0 - 2.0)
# 较低的值产生更确定性的输出
temperature: 0.7

# 最大生成 token 数
max_tokens: 1000

# 请求超时时间（秒）
timeout: 30
